# Generated by Django 3.1.3 on 2021-03-08 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSA',
            fields=[
                ('basic_details_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.basic_details')),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('referral_id', models.CharField(blank=True, max_length=15, null=True)),
                ('referred_by', models.CharField(blank=True, max_length=15, null=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            bases=('website.basic_details',),
        ),
    ]
